name: Build OpenRV Windows via Docker

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Enable Docker on Windows
        run: |
          echo "Enabling Docker (Windows)"
          choco install docker-desktop --no-progress -y
          net start com.docker.service

      - name: Pull ASWF Windows build image
        run: docker pull aswf/windows-vfx:2024

      - name: Build OpenRV inside Docker
        run: |
          docker run --rm -v "${{ github.workspace }}:/src" aswf/windows-vfx:2024 powershell -Command "
            mkdir /src/build ;
            cd /src/build ;
            cmake -S .. -B . -G 'Visual Studio 17 2022' -A x64 -DCMAKE_BUILD_TYPE=Release ;
            cmake --build . --config Release
          "

      - name: Package Installer
        run: |
          docker run --rm -v "${{ github.workspace }}:/src" aswf/windows-vfx:2024 powershell -Command "
            iscc /src/installer.iss
          "

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenRV-Windows-Installer
          path: |
            *.exe
            build/Release/**
